=== ChengSian/webconcepts/XSD/sedola.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1"
    targetNamespace="http://github.com/dret/sedola" xmlns:sedola="http://github.com/dret/sedola">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/xml.xsd">
        <xs:annotation>
            <xs:documentation>Get access to the xml: attribute groups that are in the XML namespace for XML itself.</xs:documentation>
        </xs:annotation>
    </xs:import>
    <xs:element name="service">
        <xs:annotation>
            <xs:documentation>A service in Sedola is defined as an inventory of used concepts, which are listed in the Sedola description. The list is unordered. Other services can be referenced by including their Sedola description.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="sedola:title" minOccurs="1"/>
                <xs:group ref="sedola:descriptions" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="import" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>Sedola allows inclusions which reference other Sedola descriptions and import their description as if it were copied into the referencing description. Imports can be nested. Imports must not be circular, but it is possible that inclusions form an acyclic graph (and not just a tree), so Sedola implementations have to make sure that inclusion processing correctly handles this situation.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:group ref="sedola:descriptions" minOccurs="0" maxOccurs="unbounded"
                            />
                        </xs:sequence>
                        <xs:attribute name="href" type="xs:anyURI" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="mediatype">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:group ref="sedola:descriptions" minOccurs="0"
                                    maxOccurs="unbounded"/>
                                <xs:element name="document" minOccurs="1" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:group ref="sedola:title" minOccurs="0"
                                                maxOccurs="unbounded"/>
                                            <xs:group ref="sedola:descriptions" minOccurs="0"
                                                maxOccurs="unbounded"/>
                                        </xs:sequence>
                                        <xs:attribute ref="xml:id" use="optional"/>
                                        <xs:attribute name="vocabularies" use="optional">
                                            <xs:simpleType>
                                                <xs:list itemType="xs:token"/>
                                            </xs:simpleType>
                                        </xs:attribute>
                                        <xs:attribute name="profile" type="xs:NMTOKEN"
                                            use="optional">
                                            <xs:annotation>
                                                <xs:documentation>A @profile attribute indicates that a media type's document is using a profile according to RFC 6906. It must refer to the ID of a profile that is declared in a profile element.</xs:documentation>
                                            </xs:annotation>
                                        </xs:attribute>
                                        <xs:attribute name="ref" type="xs:NMTOKEN" use="optional"/>
                                        <xs:assert test="count(@xml:id | @ref) = 1">
                                            <xs:annotation>
                                                <xs:documentation>A document in a media type is either defined (when the media type itself is defined), or it is referenced in the media type definition, when the media type is referenced.</xs:documentation>
                                            </xs:annotation>
                                        </xs:assert>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element ref="sedola:link" minOccurs="0" maxOccurs="unbounded"/>
                            </xs:sequence>
                            <xs:attribute name="def" type="sedola:mediaTypeType" use="optional"/>
                            <xs:attribute name="ref" type="sedola:mediaTypeType" use="optional"/>
                            <xs:assert test="count(@def | @ref) = 1">
                                <xs:annotation>
                                    <xs:documentation>Media types are either defined or referenced; @def and @ref are mutually exclusive.</xs:documentation>
                                </xs:annotation>
                            </xs:assert>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="profile">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:group ref="sedola:title" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:group ref="sedola:descriptions" minOccurs="0"
                                    maxOccurs="unbounded"/>
                            </xs:sequence>
                            <xs:attribute ref="xml:id" use="required"/>
                            <xs:attribute name="id" type="xs:anyURI" use="required">
                                <xs:annotation>
                                    <xs:documentation>The profile URI (which does not have to be dereferencable and thus uses @id instead of @href).</xs:documentation>
                                </xs:annotation>
                            </xs:attribute>
                        </xs:complexType>
                    </xs:element>
                    <xs:element ref="sedola:link"/>
                    <xs:element name="vocabulary">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:group ref="sedola:title" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:group ref="sedola:descriptions" minOccurs="0"
                                    maxOccurs="unbounded"/>
                            </xs:sequence>
                            <xs:attribute ref="xml:id" use="optional"/>
                            <xs:attribute name="id" type="xs:string" use="optional"/>
                            <xs:attribute name="def" type="xs:token"/>
                            <xs:attribute name="type" use="optional">
                                <xs:simpleType>
                                    <xs:union>
                                        <xs:simpleType>
                                            <xs:restriction base="xs:token">
                                                <xs:enumeration value="xmlns"/>
                                                <xs:enumeration value="FPI"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                        <xs:simpleType>
                                            <xs:restriction base="xs:token"/>
                                        </xs:simpleType>
                                    </xs:union>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="http-header">
                        <xs:complexType>
                            <xs:sequence>
                                <!-- HTTP Headers need no title, their name should serve as their title. -->
                                <xs:group ref="sedola:descriptions" minOccurs="0"
                                    maxOccurs="unbounded"/>
                                <xs:element minOccurs="0" ref="sedola:ABNF"/>
                            </xs:sequence>
                            <xs:attribute name="def" use="optional" type="sedola:httpHeaderType"/>
                            <xs:attribute name="ref" use="optional" type="sedola:httpHeaderType"/>
                            <xs:assert test="count(@def | @ref) = 1">
                                <xs:annotation>
                                    <xs:documentation>Media types are either defined or referenced; @def and @ref are mutually exclusive.</xs:documentation>
                                </xs:annotation>
                            </xs:assert>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="xs:anyURI" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="link">
        <xs:complexType>
            <xs:group ref="sedola:descriptions" minOccurs="0" maxOccurs="unbounded"/>
            <xs:attribute ref="xml:id" use="optional"/>
            <xs:attribute name="def" type="sedola:linkRelationType">
                <xs:annotation>
                    <xs:documentation source="http://tools.ietf.org/html/rfc5988#section-4">Links can be based on relations, or defined by selectors. Link relations must be names or URIs for RFC 5988 links. Links also can be encoded differently (for example in XML element names), in which case they have a selector.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="select">
                <xs:annotation>
                    <xs:documentation>Links can be selected, and the @selector attribute is used to specify the expression language of the @select attribute.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="selector">
                <xs:annotation>
                    <xs:documentation>Determines the expression language of the @select attribute.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="xpath1"/>
                        <xs:enumeration value="xpath2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="ref" type="sedola:linkRelationType">
                <xs:annotation>
                    <xs:documentation>Used to reference an existing and included link relation, that is reused. The documentation should describe how the link is used specifically in the context where it is referenced.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:group name="title">
        <xs:sequence>
            <xs:element name="title">
                <xs:complexType mixed="true">
                    <xs:attribute name="short" type="xs:string" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:group name="descriptions">
        <xs:annotation>
            <xs:documentation>This is a copy of the "description" group as it is defined and used in XSD's schema for schemas.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="appinfo" id="appinfo">
                <xs:complexType mixed="true">
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:any processContents="lax"/>
                    </xs:sequence>
                    <xs:attribute name="source" type="xs:anyURI"/>
                    <xs:anyAttribute namespace="##other" processContents="lax"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="documentation" id="documentation">
                <xs:complexType mixed="true">
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:any processContents="lax"/>
                    </xs:sequence>
                    <xs:attribute name="source" type="xs:anyURI"/>
                    <xs:attribute ref="xml:lang"/>
                    <xs:anyAttribute namespace="##other" processContents="lax"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:group>
    <xs:simpleType name="mediaTypeType">
        <xs:annotation>
            <xs:documentation>This is a type for representing media type names. It uses the media type name syntax from RFC 4288.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:token">
            <xs:pattern value="[a-zA-Z0-9!#$&amp;\.\+\-^_]+/[a-zA-Z0-9!#$&amp;\.\+\-^_]+">
                <xs:annotation>
                    <xs:documentation source="http://tools.ietf.org/html/rfc4288#section-4.2">(sub)type-name = ALPHA / DIGIT / "!" / "#" / "$" / "&amp;" / "." / "+" / "-" / "^" / "_"</xs:documentation>
                </xs:annotation>
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="httpHeaderType">
        <xs:restriction base="xs:token">
            <xs:pattern value="[!#$%&amp;'\*\+\-\.\^_`\|~0-9a-zA-Z]+">
                <xs:annotation>
                    <xs:documentation source="http://tools.ietf.org/html/draft-ietf-httpbis-p1-messaging#section-3.2">field-name = 1*( "!" / "#" / "$" / "%" / "&amp;" / "'" / "*" / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA</xs:documentation>
                </xs:annotation>
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="linkRelationType">
        <xs:union memberTypes="xs:anyURI">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:pattern value="[a-z][a-z0-9\.\-]+">
                        <xs:annotation>
                            <xs:documentation source="http://tools.ietf.org/html/rfc5988#section-5">reg-rel-type = LOALPHA *( LOALPHA | DIGIT | "." | "-" )</xs:documentation>
                        </xs:annotation>
                    </xs:pattern>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:element name="ABNF">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="src" type="xs:anyURI" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ChengSian/webconcepts/W3C/resource-hints.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title>Resource Hints</title>
    <documentation source="http://www.w3.org/TR/resource-hints/">This specification defines the dns-prefetch, preconnect, prefetch, and prerender relationships of the HTML Link Element (&lt;link>). These primitives enable the developer, and the server generating or delivering the resources, to assist the user agent in the decision process of which origins it should connect to, and which resources it should fetch and preprocess to improve page performance.</documentation>
    <link def="dns-prefetch">
        <documentation source="www.w3.org/TR/resource-hints/#dns-prefetch">The dns-prefetch link relation type is used to indicate an origin that will be used to fetch required resources, and that the user agent SHOULD resolve as early as possible.</documentation>
    </link>
    <link def="preconnect">
        <documentation source="http://www.w3.org/TR/resource-hints/#preconnect">The preconnect link relation type is used to indicate an origin that will be used to fetch required resources. Initiating an early connection, which includes the DNS lookup, TCP handshake, and optional TLS negotiation, allows the user agent to mask the high latency costs of establishing a connection.</documentation>
    </link>
    <link def="prefetch">
        <documentation source="http://www.w3.org/TR/resource-hints/#prefetch">The prefetch link relation type is used to declare a resource that might be required by the next navigation, and that the user agent SHOULD fetch, such that the user agent can deliver a faster response once the resource is requested in the future.</documentation>
    </link>
    <link def="prerender">
        <documentation source="http://www.w3.org/TR/resource-hints/#prerender">The prerender link relation type is used to declare an HTML resource that might be required by the next navigation, and that the user agent SHOULD fetch and execute, such that the user agent can deliver faster response and processing once the resource is requested in the future.</documentation>
    </link>
</service>

=== ChengSian/webconcepts/helpers/template-desc.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title short="Template Descriptions"> URI Template Descriptions</title>
    <documentation source="http://tools.ietf.org/html/draft-wilde-template-desc">Interactions with many resources on the Web are driven by and/or can be described by URI Templates. RFC 6570 says that "a URI Template is a compact sequence of characters for describing a range of Uniform Resource Identifiers through variable expansion." This specification defines Template Descriptions, a schema and a media type that can be used to document and describe a URI Template by supporting descriptive markup that allows variables to be associated with documentation (human-oriented) and/or descriptions (machine-oriented). Template Descriptions can be used by media types (by inclusion or by reference) that seek to make URI Templates self-describing, without having to create their own representation.</documentation>
    <mediatype xml:id="template-desc" type="application/td+xml">
        <resource xml:id="template-desc-document-xml">
            <title>Template Descriptions (XML)</title>
            <documentation source="http://tools.ietf.org/html/draft-wilde-template-desc#section-4.1">The Internet media type for a Template Description document is application/td+xml.</documentation>
        </resource>
    </mediatype>
    <link xml:id="template-desc-linkrel-uri-template" relation="uri-template">
        <documentation source="http://tools.ietf.org/html/draft-wilde-template-desc#section-4.1">Linking to a resource that can be used as a template description for creating a request URI for the context resource.</documentation>
    </link>
</service>

=== ChengSian/webconcepts/IETF/RFC/6903.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title>Additional Link Relation Types</title>
    <documentation source="http://tools.ietf.org/html/rfc6903">This specification defines a number of additional link relation types that can used for a range of purposes in a variety of applications types.</documentation>
    <link xml:id="rfc6903-linkrel-about" rel="about">
        <documentation source="http://tools.ietf.org/html/rfc6903#section-2">The "about" link relation can be used to refer to a resource that is the subject or topic of the link's context.  Multiple subjects can be indicated through the use of multiple "about" link relations.</documentation>
    </link>
    <link xml:id="rfc6903-linkrel-preview" rel="preview">
        <documentation source="http://tools.ietf.org/html/rfc6903#section-3">The "preview" link relation can be used to refer to a resource that serves as a preview of the link's context, likely with reduced quality or limited content.  For instance, the preview link might reference a screen capture of a video, a brief snippet of audio from a song, or a thumbnail representation of an image.</documentation>
    </link>
    <link xml:id="rfc6903-linkrel-privacy-policy" rel="privacy-policy">
        <documentation source="http://tools.ietf.org/html/rfc6596#section-4">The "privacy-policy" link relation can be used to refer to a resource describing the privacy policy associated with the link's context. The privacy policy can be any resource that discloses what personal information about the user is collected and how that personal information is stored, used, managed, and disclosed to other parties.</documentation>
    </link>
    <link xml:id="rfc6903-linkrel-terms-of-service" rel="terms-of-service">
        <documentation source="http://tools.ietf.org/html/rfc6596#section-5">The "terms-of-service" link relation can be used to refer to a resource describing the terms of service associated with the link's context.  The terms of service can be any resource that describes the rules to which a consumer of the service must agree to follow when using the service provided by the link's context.</documentation>
    </link>
    <link xml:id="rfc6903-linkrel-type" rel="type">
        <documentation source="http://tools.ietf.org/html/rfc6596#section-6">The "type" link relation can be used to indicate that the context resource is an instance of the resource identified by the target
            Internationalized Resource Identifier (IRI).</documentation>
    </link>
</service>

=== ChengSian/webconcepts/IETF/RFC/2774.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title>An HTTP Extension Framework</title>
    <documentation source="http://tools.ietf.org/html/rfc2774">A wide range of applications have proposed various extensions of the HTTP protocol. Current efforts span an enormous range, including distributed authoring, collaboration, printing, and remote procedure call mechanisms. These HTTP extensions are not coordinated, since there has been no standard framework for defining extensions and thus, separation of concerns. This document describes a generic extension mechanism for HTTP, which is designed to address the tension between private agreement and public specification and to accommodate extension of applications using HTTP clients, servers, and proxies. The proposal associates each extension with a globally unique identifier, and uses HTTP header fields to carry the extension identifier and related information between the parties involved in the extended communication.</documentation>
    <http-header def="Man">
        <documentation source="http://tools.ietf.org/html/rfc2774#section-4.1"></documentation>
    </http-header>
    <http-header def="Opt">
        <documentation source="http://tools.ietf.org/html/rfc2774#section-4.1"></documentation>
    </http-header>
    <http-header def="C-Man">
        <documentation source="http://tools.ietf.org/html/rfc2774#section-4.2"></documentation>
    </http-header>
    <http-header def="C-Opt">
        <documentation source="http://tools.ietf.org/html/rfc2774#section-4.2"></documentation>
    </http-header>
    <http-header def="Ext">
        <documentation source="http://tools.ietf.org/html/rfc2774#section-4.3"></documentation>
    </http-header>
    <http-header def="C-Ext">
        <documentation source="http://tools.ietf.org/html/rfc2774#section-4.3"></documentation>
    </http-header>
</service>

=== ChengSian/webconcepts/IETF/RFC/6271.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title>The Atom "deleted-entry" Element</title>
    <documentation source="http://tools.ietf.org/html/rfc6721">This specification adds mechanisms to the Atom Syndication Format that publishers of Atom Feed and Entry documents can use to explicitly identify Atom entries that have been removed.</documentation>
    <mediatype xml:id="atom-deleted-entry-mediatype" type="application/atomdeleted+xml">
        <document xml:id="deleted-entry" vocabularies="deleted-entry-vocabulary">
            <title>Atom Entry Document</title>
            <documentation source="http://tools.ietf.org/html/rfc6721#section-4">A "Deleted Entry Document" represents exactly one at:deleted-entry element outside the context of an Atom feed. Its root is the at:deleted-entry element.</documentation>
        </document>
    </mediatype>
    <vocabulary xml:id="atom-deleted-entry-vocabulary" id="http://purl.org/atompub/tombstones/1.0" type="xmlns">
        <title>The Atom "deleted-entry" Element XML Vocabulary</title>
        <documentation source="http://tools.ietf.org/html/rfc6721#section-3">The at:deleted-entry element represents an Atom Entry that has been removed.</documentation>
    </vocabulary>
</service>

=== ChengSian/webconcepts/W3C/appmanifest.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title>Manifest for Web Application</title>
    <documentation source="http://www.w3.org/TR/appmanifest/">This specification defines a JSON-based manifest that provides developers with a centralized place to put metadata associated with a web application. This includes, but is not limited to, the web application's name, links to icons, as well as the preferred URL to open when a user launches the web application. The manifest also allows developers to declare a default orientation for their web application, as well as providing the ability to set the display mode for the application (e.g., in fullscreen). Additionally, the manifest allows a developer to "scope" a web application to a URL. This restricts the URLs to which the application can be navigated and provides a means to "deep link" into a web application from other applications. Using this metadata, user agents can provide developers with means to create user experiences that are more comparable to that of a native application. In addition, this specification defines the manifest link type, which provides a declarative means for a document to be associated with a manifest.</documentation>
    <link def="manifest">
        <documentation source="http://www.w3.org/TR/appmanifest/#linking">Imports or links to a manifest.</documentation>
    </link>
    <mediatype def="application/manifest+json">
        <document xml:id="web-app-manifest">
            <title>Web Application Manifest</title>
            <documentation source=""></documentation>
        </document>
    </mediatype>
    <vocabulary xml:id="web-app-manifest-json-schema">
        <title>Web Application Manifest JSON Schema</title>
        <documentation source="http://www.w3.org/TR/appmanifest/#json-schema">Developers interested in validating manifest documents can find an unofficial JSON schema for the manifest format at schemastore.org. It is licensed under Apache 2.0. It is kindly maintained by Mads Kristensen. If you find any issues with the JSON schema, please file a bug at the SchemaStore repository on GitHub. </documentation>
    </vocabulary>
</service>

=== ChengSian/webconcepts/I-D/draft-nottingham-http-problem.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title short="HTTP Problem">HTTP Problem Detail</title>
    <documentation source="http://tools.ietf.org/html/draft-nottingham-http-problem">This document defines a "problem detail" as a way to carry machine-readable details of errors in a HTTP response, to avoid the need to invent new error response formats for HTTP APIs.</documentation>
    <mediatype xml:id="http-problem-json" type="application/api-problem+json">
        <document xml:id="http-problem-document-json">
            <title>HTTP Problem Detail (JSON)</title>
            <documentation source="http://tools.ietf.org/html/draft-nottingham-http-problem#section-3">The canonical model for problem details is a JSON object. When serialised as a JSON document, that format is identified with the "application/api-problem+json" media type.</documentation>
        </document>
    </mediatype>
    <mediatype xml:id="http-problem-xml" type="application/api-problem+xml">
        <document xml:id="http-problem-document-xml">
            <title>HTTP Problem Detail (XML)</title>
            <documentation source="http://tools.ietf.org/html/draft-nottingham-http-problem#appendix-A">Some HTTP-based APIs use XML as their primary format convention. Such APIs MAY express problem details using the format defined in this appendix.</documentation>
        </document>
    </mediatype>
</service>
