=== ChengSian/webconcepts/XSD/sedola.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1"
    targetNamespace="http://github.com/dret/sedola" xmlns:sedola="http://github.com/dret/sedola">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/xml.xsd">
        <xs:annotation>
            <xs:documentation>Get access to the xml: attribute groups that are in the XML namespace for XML itself.</xs:documentation>
        </xs:annotation>
    </xs:import>
    <xs:element name="service">
        <xs:annotation>
            <xs:documentation>A service in Sedola is defined as an inventory of used concepts, which are listed in the Sedola description. The list is unordered. Other services can be referenced by including their Sedola description.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="sedola:title" minOccurs="1"/>
                <xs:group ref="sedola:descriptions" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="import" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>Sedola allows inclusions which reference other Sedola descriptions and import their description as if it were copied into the referencing description. Imports can be nested. Imports must not be circular, but it is possible that inclusions form an acyclic graph (and not just a tree), so Sedola implementations have to make sure that inclusion processing correctly handles this situation.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:group ref="sedola:descriptions" minOccurs="0" maxOccurs="unbounded"
                            />
                        </xs:sequence>
                        <xs:attribute name="href" type="xs:anyURI" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="mediatype">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:group ref="sedola:descriptions" minOccurs="0"
                                    maxOccurs="unbounded"/>
                                <xs:element name="document" minOccurs="1" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:group ref="sedola:title" minOccurs="0"
                                                maxOccurs="unbounded"/>
                                            <xs:group ref="sedola:descriptions" minOccurs="0"
                                                maxOccurs="unbounded"/>
                                        </xs:sequence>
                                        <xs:attribute ref="xml:id" use="optional"/>
                                        <xs:attribute name="vocabularies" use="optional">
                                            <xs:simpleType>
                                                <xs:list itemType="xs:token"/>
                                            </xs:simpleType>
                                        </xs:attribute>
                                        <xs:attribute name="profile" type="xs:NMTOKEN"
                                            use="optional">
                                            <xs:annotation>
                                                <xs:documentation>A @profile attribute indicates that a media type's document is using a profile according to RFC 6906. It must refer to the ID of a profile that is declared in a profile element.</xs:documentation>
                                            </xs:annotation>
                                        </xs:attribute>
                                        <xs:attribute name="ref" type="xs:NMTOKEN" use="optional"/>
                                        <xs:assert test="count(@xml:id | @ref) = 1">
                                            <xs:annotation>
                                                <xs:documentation>A document in a media type is either defined (when the media type itself is defined), or it is referenced in the media type definition, when the media type is referenced.</xs:documentation>
                                            </xs:annotation>
                                        </xs:assert>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element ref="sedola:link" minOccurs="0" maxOccurs="unbounded"/>
                            </xs:sequence>
                            <xs:attribute name="def" type="sedola:mediaTypeType" use="optional"/>
                            <xs:attribute name="ref" type="sedola:mediaTypeType" use="optional"/>
                            <xs:assert test="count(@def | @ref) = 1">
                                <xs:annotation>
                                    <xs:documentation>Media types are either defined or referenced; @def and @ref are mutually exclusive.</xs:documentation>
                                </xs:annotation>
                            </xs:assert>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="profile">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:group ref="sedola:title" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:group ref="sedola:descriptions" minOccurs="0"
                                    maxOccurs="unbounded"/>
                            </xs:sequence>
                            <xs:attribute ref="xml:id" use="required"/>
                            <xs:attribute name="id" type="xs:anyURI" use="required">
                                <xs:annotation>
                                    <xs:documentation>The profile URI (which does not have to be dereferencable and thus uses @id instead of @href).</xs:documentation>
                                </xs:annotation>
                            </xs:attribute>
                        </xs:complexType>
                    </xs:element>
                    <xs:element ref="sedola:link"/>
                    <xs:element name="vocabulary">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:group ref="sedola:title" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:group ref="sedola:descriptions" minOccurs="0"
                                    maxOccurs="unbounded"/>
                            </xs:sequence>
                            <xs:attribute ref="xml:id" use="optional"/>
                            <xs:attribute name="id" type="xs:string" use="optional"/>
                            <xs:attribute name="def" type="xs:token"/>
                            <xs:attribute name="type" use="optional">
                                <xs:simpleType>
                                    <xs:union>
                                        <xs:simpleType>
                                            <xs:restriction base="xs:token">
                                                <xs:enumeration value="xmlns"/>
                                                <xs:enumeration value="FPI"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                        <xs:simpleType>
                                            <xs:restriction base="xs:token"/>
                                        </xs:simpleType>
                                    </xs:union>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="http-header">
                        <xs:complexType>
                            <xs:sequence>
                                <!-- HTTP Headers need no title, their name should serve as their title. -->
                                <xs:group ref="sedola:descriptions" minOccurs="0"
                                    maxOccurs="unbounded"/>
                                <xs:element minOccurs="0" ref="sedola:ABNF"/>
                            </xs:sequence>
                            <xs:attribute name="def" use="optional" type="sedola:httpHeaderType"/>
                            <xs:attribute name="ref" use="optional" type="sedola:httpHeaderType"/>
                            <xs:assert test="count(@def | @ref) = 1">
                                <xs:annotation>
                                    <xs:documentation>Media types are either defined or referenced; @def and @ref are mutually exclusive.</xs:documentation>
                                </xs:annotation>
                            </xs:assert>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="xs:anyURI" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="link">
        <xs:complexType>
            <xs:group ref="sedola:descriptions" minOccurs="0" maxOccurs="unbounded"/>
            <xs:attribute ref="xml:id" use="optional"/>
            <xs:attribute name="def" type="sedola:linkRelationType">
                <xs:annotation>
                    <xs:documentation source="http://tools.ietf.org/html/rfc5988#section-4">Links can be based on relations, or defined by selectors. Link relations must be names or URIs for RFC 5988 links. Links also can be encoded differently (for example in XML element names), in which case they have a selector.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="select">
                <xs:annotation>
                    <xs:documentation>Links can be selected, and the @selector attribute is used to specify the expression language of the @select attribute.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="selector">
                <xs:annotation>
                    <xs:documentation>Determines the expression language of the @select attribute.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="xpath1"/>
                        <xs:enumeration value="xpath2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="ref" type="sedola:linkRelationType">
                <xs:annotation>
                    <xs:documentation>Used to reference an existing and included link relation, that is reused. The documentation should describe how the link is used specifically in the context where it is referenced.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:group name="title">
        <xs:sequence>
            <xs:element name="title">
                <xs:complexType mixed="true">
                    <xs:attribute name="short" type="xs:string" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:group name="descriptions">
        <xs:annotation>
            <xs:documentation>This is a copy of the "description" group as it is defined and used in XSD's schema for schemas.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="appinfo" id="appinfo">
                <xs:complexType mixed="true">
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:any processContents="lax"/>
                    </xs:sequence>
                    <xs:attribute name="source" type="xs:anyURI"/>
                    <xs:anyAttribute namespace="##other" processContents="lax"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="documentation" id="documentation">
                <xs:complexType mixed="true">
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:any processContents="lax"/>
                    </xs:sequence>
                    <xs:attribute name="source" type="xs:anyURI"/>
                    <xs:attribute ref="xml:lang"/>
                    <xs:anyAttribute namespace="##other" processContents="lax"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:group>
    <xs:simpleType name="mediaTypeType">
        <xs:annotation>
            <xs:documentation>This is a type for representing media type names. It uses the media type name syntax from RFC 4288.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:token">
            <xs:pattern value="[a-zA-Z0-9!#$&amp;\.\+\-^_]+/[a-zA-Z0-9!#$&amp;\.\+\-^_]+">
                <xs:annotation>
                    <xs:documentation source="http://tools.ietf.org/html/rfc4288#section-4.2">(sub)type-name = ALPHA / DIGIT / "!" / "#" / "$" / "&amp;" / "." / "+" / "-" / "^" / "_"</xs:documentation>
                </xs:annotation>
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="httpHeaderType">
        <xs:restriction base="xs:token">
            <xs:pattern value="[!#$%&amp;'\*\+\-\.\^_`\|~0-9a-zA-Z]+">
                <xs:annotation>
                    <xs:documentation source="http://tools.ietf.org/html/draft-ietf-httpbis-p1-messaging#section-3.2">field-name = 1*( "!" / "#" / "$" / "%" / "&amp;" / "'" / "*" / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA</xs:documentation>
                </xs:annotation>
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="linkRelationType">
        <xs:union memberTypes="xs:anyURI">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:pattern value="[a-z][a-z0-9\.\-]+">
                        <xs:annotation>
                            <xs:documentation source="http://tools.ietf.org/html/rfc5988#section-5">reg-rel-type = LOALPHA *( LOALPHA | DIGIT | "." | "-" )</xs:documentation>
                        </xs:annotation>
                    </xs:pattern>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:element name="ABNF">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="src" type="xs:anyURI" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ChengSian/webconcepts/W3C/eventsource.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title>Server-Sent Events</title>
    <documentation source="http://www.w3.org/TR/eventsource/"> specification defines an API for opening an HTTP connection for receiving push notifications from a server in the form of DOM events. The API is designed such that it can be extended to work with other push notification schemes such as Push SMS.</documentation>
    <mediatype xml:id="eventsource-mediatype-text-event-stream" type="text/event-stream">
        <documentation source="http://www.w3.org/TR/eventsource/#text-event-stream">Defines a media type for representing an event stream for Server-Sent Events.</documentation>
        <document>
            <title>Event Stream</title>
            <documentation source="http://www.w3.org/TR/eventsource/#parsing-an-event-stream">An event stream as represented by Server-Sent Events.</documentation>
        </document>
    </mediatype>
    <http-header xml:id="eventsource-http-header-Last-Event-ID" name="Last-Event-ID">
        <documentation source="http://www.w3.org/TR/eventsource/#last-event-id">The Last-Event-ID HTTP header specifies the value of the event source's last event ID string, encoded as UTF-8.</documentation>
    </http-header>
</service>

=== ChengSian/webconcepts/IETF/RFC/5005.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title>Feed Paging and Archiving</title>
    <documentation source="http://tools.ietf.org/html/rfc5005">Syndicated Web feeds (using formats such as Atom) are often split into multiple documents to save bandwidth, allow "sliding window" access, or for other purposes. This specification formalizes two types of feeds that can span one or more feed documents; "paged" feeds and "archived" feeds. Additionally, it defines "complete" feeds to cover the case when a single feed document explicitly represents all of the feed's entries.</documentation>
    <link def="first">
        <documentation source="http://tools.ietf.org/html/rfc5005#section-3">A URI that refers to the furthest preceding document in a series of documents.</documentation>
    </link>
    <link def="last">
        <documentation source="http://tools.ietf.org/html/rfc5005#section-3">A URI that refers to the furthest following document in a series of documents.</documentation>
    </link>
    <link def="previous">
        <documentation source="http://tools.ietf.org/html/rfc5005#section-3">A URI that refers to the immediately preceding document in a series of documents.</documentation>
    </link>
    <link def="next">
        <documentation source="http://tools.ietf.org/html/rfc5005#section-3">A URI that refers to the immediately following document in a series of documents.</documentation>
    </link>
    <link def="prev-archive">
        <documentation source="http://tools.ietf.org/html/rfc5005#section-4">A URI that refers to the immediately preceding archive document.</documentation>
    </link>
    <link def="next-archive">
        <documentation source="http://tools.ietf.org/html/rfc5005#section-4">A URI that refers to the immediately following archive document.</documentation>
    </link>
    <link def="current">
        <documentation source="http://tools.ietf.org/html/rfc5005#section-4">A URI that, when dereferenced, returns a feed document containing the most recent entries in the feed.</documentation>
    </link>
</service>

=== ChengSian/webconcepts/helpers/http-problem.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title short="HTTP Problem">HTTP Problem Detail</title>
    <mediatype xml:id="http-problem-json" type="application/api-problem+json">
        <resource xml:id="http-problem-document-json">
            <title>HTTP Problem Detail (JSON)</title>
            <documentation source="http://tools.ietf.org/html/draft-nottingham-http-problem#section-3">The canonical model for problem details is a JSON object. When serialised as a JSON document, that format is identified with the "application/api-problem+json" media type.</documentation>
        </resource>
    </mediatype>
    <mediatype xml:id="http-problem-xml" type="application/api-problem+xml">
        <resource xml:id="http-problem-document-xml">
            <title>HTTP Problem Detail (XML)</title>
            <documentation source="http://tools.ietf.org/html/draft-nottingham-http-problem#appendix-A">Some HTTP-based APIs use XML as their primary format convention. Such APIs MAY express problem details using the format defined in this appendix.</documentation>
        </resource>
    </mediatype>
</service>

=== ChengSian/webconcepts/helpers/home-document.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title>Home Documents</title>
    <documentation source="http://tools.ietf.org/html/draft-nottingham-json-home">This document proposes a "home document" format for non-browser HTTP clients.</documentation>
    <documentation source="http://tools.ietf.org/html/draft-wilde-home-xml">The current draft for HTTP Home Documents provides a JSON syntax only. This draft provides an XML syntax for the same underlying data model, so that the concept of HTTP Home Documents can be consistently exposed in both JSON- and XML-based HTTP services.</documentation>
    <mediatype xml:id="home-document-json" type="application/home+json">
        <document xml:id="home-document-document-json">
            <title>Home Documents (JSON)</title>
            <documentation source="http://tools.ietf.org/html/draft-nottingham-json-home">This document proposes a "home document" format for non-browser HTTP clients.</documentation>
        </document>
    </mediatype>
    <mediatype xml:id="home-document-xml" type="application/home+xml">
        <document xml:id="home-document-document-xml">
            <title>Home Documents (XML)</title>
            <documentation source="http://tools.ietf.org/html/draft-wilde-home-xml">The current draft for HTTP Home Documents provides a JSON syntax only. This draft provides an XML syntax for the same underlying data model, so that the concept of HTTP Home Documents can be consistently exposed in both JSON- and XML-based HTTP services.</documentation>
        </document>
    </mediatype>
    <vocabulary xml:id="home-document-json-vocabulary">
        <title>The Home Document JSON Vocabulary</title>
        <documentation source="http://tools.ietf.org/html/draft-nottingham-json-home-03#section-2">A JSON Home Document uses the format described in RFC 4627 and has the media type "application/json-home". Its content consists of a root object with a "resources" property, whose member names are link relation types (as defined by RFC 5988), and values are Resource Objects, defined below.</documentation>
    </vocabulary>
    <vocabulary xml:id="home-document-xml-vocabulary">
        <title>The Home Document XML Vocabulary</title>
        <documentation source="http://tools.ietf.org/html/draft-wilde-home-xml-02#section-3">The following XML Schema is describing the XML shown in Section 2. Since there currently is no extension model, the XML Schema does currently not contain any extension points.</documentation>
    </vocabulary>
</service>

=== ChengSian/webconcepts/IETF/RFC/3023.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title short="XML">XML Media Types</title>
    <documentation source="http://tools.ietf.org/html/rfc3023">This document standardizes five new media types - text/xml, application/xml, text/xml-external-parsed-entity, application/xml-external-parsed-entity, and application/xml-dtd - for use in exchanging network entities that are related to the Extensible Markup Language (XML). This document also standardizes a convention (using the suffix '+xml') for naming media types outside of these five types when those media types represent XML MIME (Multipurpose Internet Mail Extensions) entities. XML MIME entities are currently exchanged via the HyperText Transfer Protocol on the World Wide Web, are an integral part of the WebDAV protocol for remote web authoring, and are expected to have utility in many domains.</documentation>
    <mediatype def="text/xml">
        <documentation source="http://tools.ietf.org/html/rfc3023#section-3.1">If an XML document - that is, the unprocessed, source XML document - is readable by casual users, text/xml is preferable to application/xml. MIME user agents (and web user agents) that do not have explicit support for text/xml will treat it as text/plain, for example, by displaying the XML MIME entity as plain text.</documentation>
    </mediatype>
    <mediatype def="application/xml">
        <documentation source="http://tools.ietf.org/html/rfc3023#section-3.2">Application/xml is preferable when an XML document is unreadable by casual users.</documentation>
    </mediatype>
    <mediatype def="text/xml-external-parsed-entity">
        <documentation source="http://tools.ietf.org/html/rfc3023#section-3.3">If an XML external parsed entity - that is, the unprocessed, source XML entity - is readable by casual users, text/xml-external-parsed-entity is preferable to application/xml-external-parsed-entity. MIME user agents (and web user agents) that do not have explicit support for text/xml-external-parsed-entity will treat it as text/plain, for example, by displaying the XML MIME entity as plain text.</documentation>
    </mediatype>
    <mediatype def="application/xml-external-parsed-entity">
        <documentation source="http://tools.ietf.org/html/rfc3023#section-3.4">Application/xml is preferable when an XML external parsed entity is unreadable by casual users.</documentation>
    </mediatype>
    <mediatype def="application/xml-dtd">
        <documentation source="http://tools.ietf.org/html/rfc3023#section-3.5">The media type application/xml-dtd SHOULD be used for "external DTD subsets" or "external parameter entities".</documentation>
    </mediatype>
</service>

=== ChengSian/webconcepts/IETF/I-D/draft-snell-more-link-relations.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title>Additional Link Relations and the urn:social Namespace</title>
    <documentation source="http://tools.ietf.org/html/draft-snell-more-link-relations">This specification defines a number of additional Link Relation Types that can used for a variety of purposes.</documentation>
    <link xml:id="snell-more-linkrel-to" rel="to">
        <documentation source="http://tools.ietf.org/html/draft-snell-more-link-relations#section-3">Refers to a resource that is considered to be part of the public primary audience of the link's context.</documentation>
    </link>
    <link xml:id="snell-more-linkrel-bto" rel="bto">
        <documentation source="http://tools.ietf.org/html/draft-snell-more-link-relations#section-3">Refers to a resource that is considered to be part of the private primary audience of the link's context.</documentation>
    </link>
    <link xml:id="snell-more-linkrel-cc" rel="cc">
        <documentation source="http://tools.ietf.org/html/draft-snell-more-link-relations#section-3">Refers to a resource that is considered to be  part of the public secondary audience of the link's context.</documentation>
    </link>
    <link xml:id="snell-more-linkrel-bcc" rel="bcc">
        <documentation source="http://tools.ietf.org/html/draft-snell-more-link-relations#section-3">Refers to a resource that is considered to be part of the private secondary audience of the link's context.</documentation>
    </link>
    <link xml:id="snell-more-linkrel-from" rel="from">
        <documentation source="http://tools.ietf.org/html/draft-snell-more-link-relations#section-3">Refers to a resource that is publicly considered to be the originator of the link's context.</documentation>
    </link>
    <link xml:id="snell-more-linkrel-bfrom" rel="bfrom">
        <documentation source="http://tools.ietf.org/html/draft-snell-more-link-relations#section-3">Refers to a resource that is privately considered to be the originator of the link's context.</documentation>
    </link>
    <link xml:id="snell-more-linkrel-source" rel="source">
        <documentation source="http://tools.ietf.org/html/draft-snell-more-link-relations#section-3">Refers to the original source of information contained by the context resource.</documentation>
    </link>
    <link xml:id="snell-more-linkrel-provider" rel="provider">
        <documentation source="http://tools.ietf.org/html/draft-snell-more-link-relations#section-3">Refers to the resource that provided the context resource. Typically, this would be used to identify the entity publishing the resource.</documentation>
    </link>
    <link xml:id="snell-more-linkrel-generator" rel="generator">
        <documentation source="http://tools.ietf.org/html/draft-snell-more-link-relations#section-3">Refers to the resource that generated the context  resource.  Typically, this would be used to identify the software application that created the context resource.</documentation>
    </link>
    <link xml:id="snell-more-linkrel-mentionedby" rel="mentionedby">
        <documentation source="http://tools.ietf.org/html/draft-snell-more-link-relations#section-3">Refers to a resource that mentions the context resource in some fashion. This, for example, would be used when an article mentions another article, or a social status update mentions a particular user, etc.</documentation>
    </link>
    <link xml:id="snell-more-linkrel-location" rel="location">
        <documentation source="http://tools.ietf.org/html/draft-snell-more-link-relations#section-3">References a URI/IRI that represents a physical or logical location with which the context resource is associated.</documentation>
    </link>
</service>
