=== ChengSian/webconcepts/XSD/sedola.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1"
    targetNamespace="http://github.com/dret/sedola" xmlns:sedola="http://github.com/dret/sedola">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/xml.xsd">
        <xs:annotation>
            <xs:documentation>Get access to the xml: attribute groups that are in the XML namespace for XML itself.</xs:documentation>
        </xs:annotation>
    </xs:import>
    <xs:element name="service">
        <xs:annotation>
            <xs:documentation>A service in Sedola is defined as an inventory of used concepts, which are listed in the Sedola description. The list is unordered. Other services can be referenced by including their Sedola description.</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:group ref="sedola:title" minOccurs="1"/>
                <xs:group ref="sedola:descriptions" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="import" minOccurs="0" maxOccurs="unbounded">
                    <xs:annotation>
                        <xs:documentation>Sedola allows inclusions which reference other Sedola descriptions and import their description as if it were copied into the referencing description. Imports can be nested. Imports must not be circular, but it is possible that inclusions form an acyclic graph (and not just a tree), so Sedola implementations have to make sure that inclusion processing correctly handles this situation.</xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:group ref="sedola:descriptions" minOccurs="0" maxOccurs="unbounded"
                            />
                        </xs:sequence>
                        <xs:attribute name="href" type="xs:anyURI" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="mediatype">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:group ref="sedola:descriptions" minOccurs="0"
                                    maxOccurs="unbounded"/>
                                <xs:element name="document" minOccurs="1" maxOccurs="unbounded">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:group ref="sedola:title" minOccurs="0"
                                                maxOccurs="unbounded"/>
                                            <xs:group ref="sedola:descriptions" minOccurs="0"
                                                maxOccurs="unbounded"/>
                                        </xs:sequence>
                                        <xs:attribute ref="xml:id" use="optional"/>
                                        <xs:attribute name="vocabularies" use="optional">
                                            <xs:simpleType>
                                                <xs:list itemType="xs:token"/>
                                            </xs:simpleType>
                                        </xs:attribute>
                                        <xs:attribute name="profile" type="xs:NMTOKEN"
                                            use="optional">
                                            <xs:annotation>
                                                <xs:documentation>A @profile attribute indicates that a media type's document is using a profile according to RFC 6906. It must refer to the ID of a profile that is declared in a profile element.</xs:documentation>
                                            </xs:annotation>
                                        </xs:attribute>
                                        <xs:attribute name="ref" type="xs:NMTOKEN" use="optional"/>
                                        <xs:assert test="count(@xml:id | @ref) = 1">
                                            <xs:annotation>
                                                <xs:documentation>A document in a media type is either defined (when the media type itself is defined), or it is referenced in the media type definition, when the media type is referenced.</xs:documentation>
                                            </xs:annotation>
                                        </xs:assert>
                                    </xs:complexType>
                                </xs:element>
                                <xs:element ref="sedola:link" minOccurs="0" maxOccurs="unbounded"/>
                            </xs:sequence>
                            <xs:attribute name="def" type="sedola:mediaTypeType" use="optional"/>
                            <xs:attribute name="ref" type="sedola:mediaTypeType" use="optional"/>
                            <xs:assert test="count(@def | @ref) = 1">
                                <xs:annotation>
                                    <xs:documentation>Media types are either defined or referenced; @def and @ref are mutually exclusive.</xs:documentation>
                                </xs:annotation>
                            </xs:assert>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="profile">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:group ref="sedola:title" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:group ref="sedola:descriptions" minOccurs="0"
                                    maxOccurs="unbounded"/>
                            </xs:sequence>
                            <xs:attribute ref="xml:id" use="required"/>
                            <xs:attribute name="id" type="xs:anyURI" use="required">
                                <xs:annotation>
                                    <xs:documentation>The profile URI (which does not have to be dereferencable and thus uses @id instead of @href).</xs:documentation>
                                </xs:annotation>
                            </xs:attribute>
                        </xs:complexType>
                    </xs:element>
                    <xs:element ref="sedola:link"/>
                    <xs:element name="vocabulary">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:group ref="sedola:title" minOccurs="0" maxOccurs="unbounded"/>
                                <xs:group ref="sedola:descriptions" minOccurs="0"
                                    maxOccurs="unbounded"/>
                            </xs:sequence>
                            <xs:attribute ref="xml:id" use="optional"/>
                            <xs:attribute name="id" type="xs:string" use="optional"/>
                            <xs:attribute name="def" type="xs:token"/>
                            <xs:attribute name="type" use="optional">
                                <xs:simpleType>
                                    <xs:union>
                                        <xs:simpleType>
                                            <xs:restriction base="xs:token">
                                                <xs:enumeration value="xmlns"/>
                                                <xs:enumeration value="FPI"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                        <xs:simpleType>
                                            <xs:restriction base="xs:token"/>
                                        </xs:simpleType>
                                    </xs:union>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="http-header">
                        <xs:complexType>
                            <xs:sequence>
                                <!-- HTTP Headers need no title, their name should serve as their title. -->
                                <xs:group ref="sedola:descriptions" minOccurs="0"
                                    maxOccurs="unbounded"/>
                                <xs:element minOccurs="0" ref="sedola:ABNF"/>
                            </xs:sequence>
                            <xs:attribute name="def" use="optional" type="sedola:httpHeaderType"/>
                            <xs:attribute name="ref" use="optional" type="sedola:httpHeaderType"/>
                            <xs:assert test="count(@def | @ref) = 1">
                                <xs:annotation>
                                    <xs:documentation>Media types are either defined or referenced; @def and @ref are mutually exclusive.</xs:documentation>
                                </xs:annotation>
                            </xs:assert>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="id" type="xs:anyURI" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="link">
        <xs:complexType>
            <xs:group ref="sedola:descriptions" minOccurs="0" maxOccurs="unbounded"/>
            <xs:attribute ref="xml:id" use="optional"/>
            <xs:attribute name="def" type="sedola:linkRelationType">
                <xs:annotation>
                    <xs:documentation source="http://tools.ietf.org/html/rfc5988#section-4">Links can be based on relations, or defined by selectors. Link relations must be names or URIs for RFC 5988 links. Links also can be encoded differently (for example in XML element names), in which case they have a selector.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="select">
                <xs:annotation>
                    <xs:documentation>Links can be selected, and the @selector attribute is used to specify the expression language of the @select attribute.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="selector">
                <xs:annotation>
                    <xs:documentation>Determines the expression language of the @select attribute.</xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:token">
                        <xs:enumeration value="xpath1"/>
                        <xs:enumeration value="xpath2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="ref" type="sedola:linkRelationType">
                <xs:annotation>
                    <xs:documentation>Used to reference an existing and included link relation, that is reused. The documentation should describe how the link is used specifically in the context where it is referenced.</xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    <xs:group name="title">
        <xs:sequence>
            <xs:element name="title">
                <xs:complexType mixed="true">
                    <xs:attribute name="short" type="xs:string" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:group>
    <xs:group name="descriptions">
        <xs:annotation>
            <xs:documentation>This is a copy of the "description" group as it is defined and used in XSD's schema for schemas.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="appinfo" id="appinfo">
                <xs:complexType mixed="true">
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:any processContents="lax"/>
                    </xs:sequence>
                    <xs:attribute name="source" type="xs:anyURI"/>
                    <xs:anyAttribute namespace="##other" processContents="lax"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="documentation" id="documentation">
                <xs:complexType mixed="true">
                    <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:any processContents="lax"/>
                    </xs:sequence>
                    <xs:attribute name="source" type="xs:anyURI"/>
                    <xs:attribute ref="xml:lang"/>
                    <xs:anyAttribute namespace="##other" processContents="lax"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
    </xs:group>
    <xs:simpleType name="mediaTypeType">
        <xs:annotation>
            <xs:documentation>This is a type for representing media type names. It uses the media type name syntax from RFC 4288.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:token">
            <xs:pattern value="[a-zA-Z0-9!#$&amp;\.\+\-^_]+/[a-zA-Z0-9!#$&amp;\.\+\-^_]+">
                <xs:annotation>
                    <xs:documentation source="http://tools.ietf.org/html/rfc4288#section-4.2">(sub)type-name = ALPHA / DIGIT / "!" / "#" / "$" / "&amp;" / "." / "+" / "-" / "^" / "_"</xs:documentation>
                </xs:annotation>
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="httpHeaderType">
        <xs:restriction base="xs:token">
            <xs:pattern value="[!#$%&amp;'\*\+\-\.\^_`\|~0-9a-zA-Z]+">
                <xs:annotation>
                    <xs:documentation source="http://tools.ietf.org/html/draft-ietf-httpbis-p1-messaging#section-3.2">field-name = 1*( "!" / "#" / "$" / "%" / "&amp;" / "'" / "*" / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA</xs:documentation>
                </xs:annotation>
            </xs:pattern>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="linkRelationType">
        <xs:union memberTypes="xs:anyURI">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:pattern value="[a-z][a-z0-9\.\-]+">
                        <xs:annotation>
                            <xs:documentation source="http://tools.ietf.org/html/rfc5988#section-5">reg-rel-type = LOALPHA *( LOALPHA | DIGIT | "." | "-" )</xs:documentation>
                        </xs:annotation>
                    </xs:pattern>
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    <xs:element name="ABNF">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="src" type="xs:anyURI" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ChengSian/webconcepts/IETF/RFC/4287.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title short="Atom">Atom Syndication Format</title>
    <documentation source="http://tools.ietf.org/html/rfc4287">Atom is an XML-based document format that describes lists of related information known as "feeds". Feeds are composed of a number of items, known as "entries", each with an extensible set of attached metadata. For example, each entry has a title.</documentation>
    <mediatype def="application/atom+xml">
        <document xml:id="atom-document-feed" vocabularies="atom-vocabulary">
            <title>Atom Feed Document</title>
            <documentation source="http://tools.ietf.org/html/rfc4287#section-2">An Atom Feed Document is a representation of an Atom feed, including metadata about the feed, and some or all of the entries associated with it. Its root is the atom:feed element.</documentation>
        </document>
        <document xml:id="atom-document-entry" vocabularies="atom-vocabulary">
            <title>Atom Entry Document</title>
            <documentation source="http://tools.ietf.org/html/rfc4287#section-2">An Atom Entry Document represents exactly one Atom entry, outside of the context of an Atom feed. Its root is the atom:entry element.</documentation>
        </document>
        <link xml:id="atom-link-uri">
            <title>atom:uri</title>
            <documentation source="http://tools.ietf.org/html/rfc4287#section-3.2.2">The "atom:uri" element's content conveys an IRI associated with the person. Person constructs MAY contain an atom:uri element, but MUST NOT contain more than one.</documentation>
        </link>
        <link xml:id="atom-link-content-src">
            <title>atom:content/@src</title>
            <documentation source="http://tools.ietf.org/html/rfc4287#section-4.1.3.2">atom:content MAY have a "src" attribute, whose value MUST be an IRI reference. If the "src" attribute is present, atom:content MUST be empty. Atom Processors MAY use the IRI to retrieve the content and MAY choose to ignore remote content or to present it in a different manner than local content.</documentation>
        </link>
        <link xml:id="atom-link-category-scheme">
            <title>atom:category/@scheme</title>
            <documentation source="http://tools.ietf.org/html/rfc4287#section-4.2.2.2">The "scheme" attribute is an IRI that identifies a categorization scheme. Category elements MAY have a "scheme" attribute.</documentation>
        </link>
        <link xml:id="atom-link-generator-uri">
            <title>atom:generator/@uri</title>
            <documentation source="http://tools.ietf.org/html/rfc4287#section-4.2.4">The atom:generator element MAY have a "uri" attribute whose value MUST be an IRI reference. When dereferenced, the resulting URI (mapped from an IRI, if necessary) SHOULD produce a representation that is relevant to that agent.</documentation>
        </link>
        <link xml:id="atom-link-icon">
            <title>atom:icon</title>
            <documentation source="http://tools.ietf.org/html/rfc4287#section-4.2.5">The "atom:icon" element's content is an IRI reference that identifies an image that provides iconic visual identification for a feed.</documentation>
        </link>
        <link xml:id="atom-link-id">
            <title>atom:id</title>
            <documentation source="http://tools.ietf.org/html/rfc4287#section-4.2.6">The "atom:id" element conveys a permanent, universally unique identifier for an entry or feed. Its content MUST be an IRI. Note that the definition of "IRI" excludes relative references. Though the IRI might use a dereferencable scheme, Atom Processors MUST NOT assume it can be dereferenced.</documentation>
        </link>
        <link xml:id="atom-link-link-href">
            <title>atom:link/@href</title>
            <documentation source="http://tools.ietf.org/html/rfc4287#section-4.2.7.1">The "href" attribute contains the link's IRI. atom:link elements MUST have an href attribute, whose value MUST be a IRI reference.</documentation>
        </link>
        <link xml:id="atom-link-logo">
            <title>atom:logo</title>
            <documentation source="http://tools.ietf.org/html/rfc4287#section-4.2.8">The "atom:logo" element's content is an IRI reference that identifies an image that provides visual identification for a feed.</documentation>
        </link>
    </mediatype>
    <link def="alternate">
        <documentation source="http://tools.ietf.org/html/rfc4287#section-4.2.7.2">The value "alternate" signifies that the IRI in the value of the href attribute identifies an alternate version of the resource described by the containing element.</documentation>
    </link>
    <link def="related">
        <documentation source="http://tools.ietf.org/html/rfc4287#section-4.2.7.2">The value "related" signifies that the IRI in the value of the href attribute identifies a resource related to the resource described by the containing element. For example, the feed for a site that discusses the performance of the search engine at "http://search.example.com" might contain, as a child of atom:feed: &lt;link rel="related" href="http://search.example.com/"/> An identical link might appear as a child of any atom:entry whose content contains a discussion of that same search engine.</documentation>
    </link>
    <link def="self">
        <documentation source="http://tools.ietf.org/html/rfc4287#section-4.2.7.2">The value "self" signifies that the IRI in the value of the href attribute identifies a resource equivalent to the containing element.</documentation>
    </link>
    <link def="enclosure">
        <documentation source="http://tools.ietf.org/html/rfc4287#section-4.2.7.2">The value "enclosure" signifies that the IRI in the value of the href attribute identifies a related resource that is potentially large in size and might require special handling. For atom:link elements with rel="enclosure", the length attribute SHOULD be provided.</documentation>
    </link>
    <link def="via">
        <documentation source="http://tools.ietf.org/html/rfc4287#section-4.2.7.2">The value "via" signifies that the IRI in the value of the href attribute identifies a resource that is the source of the information provided in the containing element.</documentation>
    </link>
    <vocabulary def="http://www.w3.org/2005/Atom" type="xmlns">
        <title>The Atom XML Vocabulary</title>
        <documentation source="http://tools.ietf.org/html/rfc4287#appendix-B">The Relax NG schema explicitly excludes elements in the Atom namespace that are not defined in this revision of the specification.</documentation>
    </vocabulary>
</service>

=== ChengSian/webconcepts/feeds/atompub.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title short="AtomPub">Atom Publishing Protocol</title>
    <include href="atom.xml"/>
    <mediatype xml:id="atompub-category" type="application/atomcat+xml">
        <documentation source="http://tools.ietf.org/html/rfc5023#section-16.1">An Atom Publishing Protocol Category Document, when serialized as XML 1.0, can be identified with the following media type.</documentation>
        <document xml:id="atompub-categorydoc" vocabularies="atompub-vocabulary">
            <title>Atom Category Document</title>
            <documentation source="http://tools.ietf.org/html/rfc5023#section-7">Category Documents contain lists of categories described using the "atom:category" element from the Atom Syndication Format.</documentation>
        </document>
    </mediatype>
    <mediatype xml:id="atompub-service" type="application/atomsvc+xml">
        <documentation source="http://tools.ietf.org/html/rfc5023#section-16.2">An Atom Publishing Protocol Service Document, when serialized as XML 1.0, can be identified with the following media type.</documentation>
        <document xml:id="atompub-servicedoc" vocabularies="atompub-vocabulary">
            <title>Atom Service Document</title>
            <documentation source="http://tools.ietf.org/html/rfc5023#section-8">For authoring to commence, a client needs to discover the capabilities and locations of the available Collections. Service Documents are designed to support this discovery process.</documentation>
        </document>
    </mediatype>
    <link xml:id="atompub-linkrel-edit" relation="edit">
        <documentation source="http://tools.ietf.org/html/rfc5023#section-11.1">The value of "edit" specifies that the value of the href attribute is the IRI of an editable Member Entry. When appearing within an atom:entry, the href IRI can be used to retrieve, update, and delete the Resource represented by that Entry. An atom:entry MUST NOT contain more than one "edit" link relation.</documentation>
    </link>
    <link xml:id="atompub-linkrel-edit-media" relation="edit-media">
        <documentation source="http://tools.ietf.org/html/rfc5023#section-11.2">When appearing within an atom:entry, the value of the href attribute is an IRI that can be used to modify a Media Resource associated with that Entry.</documentation>
    </link>
    <vocabulary xml:id="atompub-vocabulary" id="http://www.w3.org/2007/app" type="xmlns">
        <title>The AtomPub Vocabulary</title>
        <documentation source="http://tools.ietf.org/html/rfc5023#appendix-B">The Relax NG schema explicitly excludes elements in the Atom Protocol namespace that are not defined in this revision of the specification.</documentation>
    </vocabulary>
    <http-header xml:id="atompub-slug" id="Slug" type="entity">
        <documentation source="http://tools.ietf.org/html/rfc5023#section-9.7">Slug is an HTTP entity-header whose presence in a POST to a Collection constitutes a request by the client to use the header's value as part of any URIs that would normally be used to retrieve the to-be-created Entry or Media Resources.</documentation>
    </http-header>
</service>

=== ChengSian/webconcepts/IETF/RFC/5829.xml
<?xml version="1.0" encoding="UTF-8" ?>
<service xsi:noNamespaceSchemaLocation="../../core/sedola.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title>Link Relation Types for Simple Version Navigation between Web Resources</title>
    <documentation source="http://tools.ietf.org/html/rfc5829">This specification defines a set of link relation types that may be used on Web resources for navigation between a resource and other resources related to version control, such as past versions and working copies.</documentation>
    <link xml:id="rfc6573-linkrel-version-history" rel="version-history">
        <documentation source="http://tools.ietf.org/html/rfc5829#section-3.1">When included on a versioned resource, this link points to a resource containing the version history for this resource.</documentation>
    </link>
    <link xml:id="rfc6573-linkrel-latest-version" rel="latest-version">
        <documentation source="http://tools.ietf.org/html/rfc5829#section-3.2">When included on a versioned resource, this link points to a resource containing the latest (e.g., current) version.</documentation>
    </link>
    <link xml:id="rfc6573-linkrel-working-copy" rel="working-copy">
        <documentation source="http://tools.ietf.org/html/rfc5829#section-3.3">When included on a versioned resource, this link points to a working copy for this resource.</documentation>
    </link>
    <link xml:id="rfc6573-linkrel-working-copy-of" rel="working-copy-of">
        <documentation source="http://tools.ietf.org/html/rfc5829#section-3.4">When included on a working copy, this link points to the versioned resource from which this working copy was obtained.</documentation>
    </link>
    <link xml:id="rfc6573-linkrel-predecessor-version" rel="predecessor-version">
        <documentation source="http://tools.ietf.org/html/rfc5829#section-3.5">When included on a versioned resource, this link points to a resource containing the predecessor version in the version history.</documentation>
    </link>
    <link xml:id="rfc6573-linkrel-successor-version" rel="successor-version">
        <documentation source="http://tools.ietf.org/html/rfc5829#section-3.6">When included on a versioned resource, this link points to a resource containing the successor version in the version history.</documentation>
    </link>
</service>
